git clone https://github.com/mu71l473d/PublicBashScripts.git;
git clone https://github.com/mu71l473d/BashScripts.git;
git clone https://github.com/mu71l473d/BookNotes.git; 
git clone https://github.com/mu71l473d/GreyBlackHatPython.git; 
git clone https://github.com/mu71l473d/PythonScripts.git;
git clone https://github.com/mu71l473d/PowershellScripts.git;
git clone https://github.com/mu71l473d/BanditChallenge.git;
git clone https://github.com/mu71l473d/JavaProjects.git;
git clone https://github.com/mu71l473d/hacking-taoe.git;
git clone https://github.com/mu71l473d/PublicPythonScripts.git
git clone https://github.com/mu71l473d/mu71l473d.github.io.git
git clone https://github.com/mu71l473d/PublicPowerShellScripts.git
git clone https://github.com/mu71l473d/MagicMirror.git
git clone https://github.com/mu71l473d/CProgrammingLanguage.git
git clone https://github.com/mu71l473d/PublicPythonScripts.git;
git clone https://github.com/mu71l473d/mu71l473d.github.io.git;
git clone https://github.com/mu71l473d/PublicPowerShellScripts.git;
git clone https://github.com/mu71l473d/MagicMirror.git;
git clone https://github.com/mu71l473d/CProgrammingLanguage.git;

